<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ipynb</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\#Output\[.*\]</string>
	<key>foldingStopMarker</key>
	<string>\#\/Output</string>
	<key>name</key>
	<string>IPython Notebook</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\#Input-R\[.*\]
</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>ipynb.source.input.r source.r</string>
			<key>end</key>
			<string>\#\/Input</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.r</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#Markdown
</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>ipynb.text.tex.latex text.tex.latex</string>
			<key>end</key>
			<string>\#\/Markdown</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.tex.latex</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#Input\[(.*)\]\n</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>ipynb.source.input.python source.python</string>
			<key>end</key>
			<string>(\#\/Input\[\1\])$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ipynb_input_python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#Output\[.*\]
</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>ipynb.source.invisible</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>ipynb.source.output</string>
			<key>end</key>
			<string>\#\/Output</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>ipynb.source.invisible</string>
				</dict>
			</dict>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ipynb_input_python</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python_no_brackets</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ipynb</string>
	<key>uuid</key>
	<string>a09ea990-df95-11e2-a28f-0800200c9a66</string>
</dict>
</plist>
