<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ipynb</string>
	</array>
	<key>name</key>
	<string>IPython Notebook</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Beginning of cell input</string>
			<key>match</key>
			<string>Input\[.*\]</string>
			<key>name</key>
			<string>keyword.source.python</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#Input\[.*\]</string>
			<key>end</key>
			<string>\#\/Input</string>
			<key>name</key>
			<string>ipynb.source.input</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%%R</string>
					<key>end</key>
					<string>\z</string>
					<key>name</key>
					<string>ipynb.source.input.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.r</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\#Output\[.*\]</string>
			<key>end</key>
			<string>\#\/Output</string>
			<key>name</key>
			<string>ipynb.source.output</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ipynb</string>
	<key>uuid</key>
	<string>ca03e733-04ef-4330-9a6b-9b99aae1c418</string>
</dict>
</plist>
